providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --omit=dev"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "node index.js"
